### ISSUE TITLE
Categories import - structures not working?

### ISSUE THREAD

**Issue by brettgullan** [clearbold/craftimport#7]
Hello,

I'm trying out your 'export' and 'import' plugins. I have a structured set of Categories (with three levels of parent-child relationships). I've exported these and then imported the resulting .csv file. 

The category entries are recreated, but the structure is lost.

Does the plugin support nested Categories? Any thoughts on how to achieve that?

Many thanks,

Brett

**Comment by circa1977** [comment]
Hi, Brett!

I created this as a one-off for a client project to migrate an EE blog to Craft 1 year ago.

At the time, Craft did not yet support Categories, so the code written was specifically for 1 level of blog categories to map to Craft's Tags.

You'll want to take a look at line 90 in the [CraftImportService.php](https://github.com/clearbold/craftimport/blob/master/services/CraftImportService.php) file to rework it or expand it to support Craft's categories.

It's just parsing XML, so you should be able to get it working for multiple levels, too.

Mark

**Comment by brettgullan** [comment]
Thanks Mark! I'll see what I can do with it. Cheers, Brett
